# This file is useed by VSCode to setup a development environment for the project.
# It is not the same environment used in production, but rather it is optimzed
# for development.
#
# The environment contains a main "workspace" container plus a number of
# supporting application containers. D.g. db (postgres) and cache (redis).

version: '3.8'
services:
  workspace:
    # The workspace container is a python3.11 container exteded by the Dockerfile
    # with extra dependences and common tools for development. The project folder
    # is mouned inside this container at the path /main and it is in this container
    # where Visual Studio Code runs in when developing.
    #
    # Significantly this container is a privileged container, meaning it can run
    # docker commands. This is used to run the tests and other tasks that require
    # docker.
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/main:cached

      # Uncomment the next line to use Docker from inside the container. See https://aka.ms/vscode-remote/samples/docker-from-docker-compose for details.
      - /var/run/docker.sock:/var/run/docker.sock 

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"

    environment:
      USER: dist 
    user: dist
