#!/bin/sh
BIN_DIR=`dirname $0`
WORKSPACE_DIR=`dirname $BIN_DIR`
cd $WORKSPACE_DIR

echo "Fixing code..."

echo "isort..."
bin/isort app docs/conf.py

echo "black..."
bin/black app docs/conf.py

echo "Done."
